// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseUsb() {
  return window['go']['main']['App']['CloseUsb']();
}

export function DfddfScanAddress() {
  return window['go']['main']['App']['DfddfScanAddress']();
}

export function DfddfSetAddress(arg1, arg2) {
  return window['go']['main']['App']['DfddfSetAddress'](arg1, arg2);
}

export function DfddfTestAddress(arg1) {
  return window['go']['main']['App']['DfddfTestAddress'](arg1);
}

export function GetUsbStatus() {
  return window['go']['main']['App']['GetUsbStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenUsb() {
  return window['go']['main']['App']['OpenUsb']();
}

export function ReConnect() {
  return window['go']['main']['App']['ReConnect']();
}
