// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseUsb():Promise<any>;

export function DfddfScanAddress():Promise<any>;

export function DfddfSetAddress(arg1:number,arg2:number):Promise<any>;

export function DfddfTestAddress(arg1:number):Promise<any>;

export function GetUsbStatus():Promise<any>;

export function Greet(arg1:string):Promise<string>;

export function OpenUsb():Promise<any>;

export function ReConnect():Promise<any>;
